Rempve conditional logic from main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,9 +20,9 @@ jobs:
         run: python -m unittest tests/sum_test.py 
 
       # Add a conditional step to check test status
-      - name: Check Test Status
-        run: |
-          if [ $? -ne 0 ]; then
-            echo "Tests failed. Blocking the push."
-            exit 1
-          fi
+      # - name: Check Test Status
+      #   run: |
+      #     if [ $? -ne 0 ]; then
+      #       echo "Tests failed. Blocking the push."
+      #       exit 1
+      #     fi
