Fixed bug in main.yml file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,15 +13,15 @@ jobs:
         with:
           python-version: ${{ matrix.python-version }}
           architecture: x64
-     - name: Install dependencies
-       run: pip install -r requirements.txt 
-     - name: Run Test
-       run: python -m unittest tests/sum_test.py 
+      - name: Install dependencies
+        run: pip install -r requirements.txt 
+      - name: Run Test
+        run: python -m unittest tests/sum_test.py 
 
       # Add a conditional step to check test status
-     - name: Check Test Status
-       run: |
-         if [ $? -ne 0 ]; then
-           echo "Tests failed. Blocking the push."
-           exit 1
-         fi
+      - name: Check Test Status
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Tests failed. Blocking the push."
+            exit 1
+          fi
